In [1]:
!pip install mysql-connector-python

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mysql-connector-python in c:\users\emddj\appdata\roaming\python\python310\site-packages (8.3.0)

[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [44]:
import mysql.connector
import pandas as pd

connect = mysql.connector.connect(
    host='database-1.cd08osauaz8j.us-east-2.rds.amazonaws.com',
    port=3306,
    user='admin',
    password='ghkcjs123',
    database='zerobase'
)

In [2]:
df = pd.read_csv('sandwich.csv')
df.head()

   Rank                    Cafe               Menu  Price              Address
0     1             Old Oak Tap                BLT   $10.  2109 W. Chicago Ave
1     2               Au Cheval      Fried Bologna    $9.   800 W. Randolph St
2     3                    Xoco  Woodland Mushroom  $9.50      445 N. Clark St
3     4               Al’s Deli         Roast Beef  $9.40         914 Noyes St
4     5  Publican Quality Meats               PB&L   $10.    825 W. Fulton Mkt

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rank     50 non-null     int64
 1   Cafe     50 non-null     object
 2   Menu     50 non-null     object
 3   Price    50 non-null     object
 4   Address  50 non-null     object
dtypes: int64(1), object(4)
memory usage: 2.1+ KB

In [4]:
df['Price'] = df['Price'].str.replace('$', '')
df['Price'] = df['Price'].str.rstrip('.')
df['Price'] = df['Price'].astype('float')
df

,Rank,Cafe,Menu,Price,Address
0,1,Old Oak Tap,BLT,10.00,2109 W. Chicago Ave
1,2,Au Cheval,Fried Bologna,9.00,800 W. Randolph St
2,3,Xoco,Woodland Mushroom,9.50,445 N. Clark St
3,4,Al’s Deli,Roast Beef,9.40,914 Noyes St
4,5,Publican Quality Meats,PB&L,10.00,825 W. Fulton Mkt
5,6,Hendrickx Belgian Bread Crafter,Belgian Chicken Curry Salad,7.25,100 E. Walton St
6,7,Acadia,Lobster Roll,16.00,1639 S. Wabash Ave
7,8,Birchwood Kitchen,Smoked Salmon Salad,10.00,2211 W. North Ave
8,9,Cemitas Puebla,Atomica Cemitas,9.00,3619 W. North Ave
9,10,Nana,Grilled Laughing Bird Shrimp and Fried Po’ Boy,17.00,3267 S. Halsted St
10,11,Lula Cafe,Ham and Raclette Panino,11.00,2537 N. Kedzie Blvd
11,12,Ricobene’s,Breaded Steak,5.49,Multiple location
12,13,Frog n Snail,The Hawkeye,14.00,3124 N. Broadwa
13,14,Crosby’s Kitchen,Chicken Dip,10.00,3455 N. Southport Ave
14,15,Longman & Eagle,Wild Boar Sloppy Joe,13.00,2657 N. Kedzie Ave
15,16,Bari,Meatball Sub,4.50,1120 W. Grand Ave
16,17,Manny’s,Corned Beef,11.95,1141 S. Jefferson St
17,18,Eggy’s,Turkey Club,11.50,333 E. Benton Pl
18,19,Old Jerusalem,Falafel,6.25,1411 N. Wells St
19,20,Mindy’s HotChocolate,Crab Cake,15.00,1747 N. Damen Ave
20,21,Olga’s Delicatessen,Chicken Schnitzel,5.00,3209 W. Irving Park Rd
21,22,Dawali Mediterranean Kitchen,Shawarma,6.00,Multiple location
22,23,Big Jones,Toasted Pimiento Cheese,8.00,5347 N. Clark St
23,24,La Pane,Vegetarian Panino,5.99,2954 W. Irving Park Rd
24,25,Pastoral,Cali Chèvre,7.52,Multiple location
25,26,Max’s Deli,Pastrami,11.95,191 Skokie Valley Rd
26,27,Lucky’s Sandwich Co.,The Fredo,7.50,Multiple location
27,28,City Provisions,Smoked Ham,12.95,1818 W. Wilson Ave
28,29,Papa’s Cache Sabroso,Jibarito,7.00,2517 W. Division St
29,30,Bavette’s Bar & Boeuf,Shaved Prime Rib,21.00,218 W. Kinzie St
30,31,Hannah’s Bretzel,Serrano Ham and Manchego Cheese,9.79,Multiple location
31,32,La Fournette,Tuna Salad,9.75,1547 N. Wells St
32,33,Paramount Room,Paramount Reuben,13.00,415 N. Milwaukee Ave
33,34,Melt Sandwich Shoppe,The Istanbul,7.95,1840 N. Damen Ave
34,35,Floriole Cafe & Bakery,B.A.D.,9.00,1220 W. Webster Ave
35,36,First Slice Pie Café,Duck Confit and Mozzarella,9.00,5357 N. Ashland Ave
36,37,Troquet,Croque Monsieur,8.00,1834 W. Montrose Ave
37,38,Grahamwich,Green Garbanzo,8.00,615 N. State St
38,39,Saigon Sisters,The Hen House,7.00,Multiple location
39,40,Rosalia’s Deli,Tuscan Chicken,6.00,241 N. York Rd
40,41,Z&H MarketCafe,The Marty,7.25,1323 E. 57th St
41,42,Market House on the Square,Whitefish,11.00,655 Forest Ave
42,43,Elaine’s Coffee Call,"Oat Bread, Pecan Butter, and Fruit Jam",6.00,Hotel Lincol
43,44,Marion Street Cheese Market,Cauliflower Melt,9.00,100 S. Marion St
44,45,Cafecito,Cubana,5.49,26 E. Congress Pkwy
45,46,Chickpea,Kufta,8.00,2018 W. Chicago Ave
46,47,The Goddess and Grocer,Debbie’s Egg Salad,6.50,25 E. Delaware Pl
47,48,Zenwich,Beef Curry,7.50,416 N. York St
48,49,Toni Patisserie,Le Végétarien,8.75,65 E. Washington St
49,50,Phoebe’s Bakery,The Gatsby,6.85,3351 N. Broadwa

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rank     50 non-null     int64
 1   Cafe     50 non-null     object
 2   Menu     50 non-null     object
 3   Price    50 non-null     float64
 4   Address  50 non-null     object
dtypes: float64(1), int64(1), object(3)
memory usage: 2.1+ KB

In [49]:
sql = 'create table sandwich (ranking int, cafe varchar(32), menu varchar(32), price float, address varchar(32))'
cursor = connect.cursor(buffered=True)
cursor.execute(sql)

In [50]:
cursor.execute('desc sandwich')
result = cursor.fetchall()

for row in result:
    print(row)

('ranking', 'int', 'YES', '', None, '')
('cafe', 'varchar(32)', 'YES', '', None, '')
('menu', 'varchar(32)', 'YES', '', None, '')
('price', 'float', 'YES', '', None, '')
('address', 'varchar(32)', 'YES', '', None, '')

In [51]:
sql = 'insert into sandwich values (%s, %s, %s, %s, %s)'

for i, row in df.iterrows():
    cursor.execute(sql, tuple(row))
    print(tuple(row))
    connect.commit()

(1, 'Old Oak Tap', 'BLT', 10.0, '2109 W. Chicago Ave')
(2, 'Au Cheval', 'Fried Bologna', 9.0, '800 W. Randolph St')
(3, 'Xoco', 'Woodland Mushroom', 9.5, ' 445 N. Clark St')
(4, 'Al’s Deli', 'Roast Beef', 9.4, ' 914 Noyes St')
(5, 'Publican Quality Meats', 'PB&L', 10.0, '825 W. Fulton Mkt')
(6, 'Hendrickx Belgian Bread Crafter', 'Belgian Chicken Curry Salad', 7.25, ' 100 E. Walton St')
(7, 'Acadia', 'Lobster Roll', 16.0, '1639 S. Wabash Ave')
(8, 'Birchwood Kitchen', 'Smoked Salmon Salad', 10.0, '2211 W. North Ave')
(9, 'Cemitas Puebla', 'Atomica Cemitas', 9.0, '3619 W. North Ave')
(10, 'Nana', 'Grilled Laughing Bird Shrimp and Fried Po’ Boy', 17.0, '3267 S. Halsted St')
(11, 'Lula Cafe', 'Ham and Raclette Panino', 11.0, '2537 N. Kedzie Blvd')
(12, 'Ricobene’s', 'Breaded Steak', 5.49, ' Multiple location')
(13, 'Frog n Snail', 'The Hawkeye', 14.0, '3124 N. Broadwa')
(14, 'Crosby’s Kitchen', 'Chicken Dip', 10.0, '3455 N. Southport Ave')
(15, 'Longman & Eagle', 'Wild Boar Sloppy Joe', 13.0, '2657 N. Kedzie Ave')
(16, 'Bari', 'Meatball Sub', 4.5, ' 1120 W. Grand Ave')
(17, 'Manny’s', 'Corned Beef', 11.95, ' 1141 S. Jefferson St')
(18, 'Eggy’s', 'Turkey Club', 11.5, ' 333 E. Benton Pl')
(19, 'Old Jerusalem', 'Falafel', 6.25, ' 1411 N. Wells St')
(20, 'Mindy’s HotChocolate', 'Crab Cake', 15.0, '1747 N. Damen Ave')
(21, 'Olga’s Delicatessen', 'Chicken Schnitzel', 5.0, '3209 W. Irving Park Rd')
(22, 'Dawali Mediterranean Kitchen', 'Shawarma', 6.0, 'Multiple location')
(23, 'Big Jones', 'Toasted Pimiento Cheese', 8.0, '5347 N. Clark St')
(24, 'La Pane', 'Vegetarian Panino', 5.99, ' 2954 W. Irving Park Rd')
(25, 'Pastoral', 'Cali Chèvre', 7.52, ' Multiple location')
(26, 'Max’s Deli', 'Pastrami', 11.95, ' 191 Skokie Valley Rd')
(27, 'Lucky’s Sandwich Co.', 'The Fredo', 7.5, ' Multiple location')
(28, 'City Provisions', 'Smoked Ham', 12.95, ' 1818 W. Wilson Ave')
(29, 'Papa’s Cache Sabroso', 'Jibarito', 7.0, '2517 W. Division St')
(30, 'Bavette’s Bar & Boeuf', 'Shaved Prime Rib', 21.0, '218 W. Kinzie St')
(31, 'Hannah’s Bretzel', 'Serrano Ham and Manchego Cheese', 9.79, ' Multiple location')
(32, 'La Fournette', 'Tuna Salad', 9.75, ' 1547 N. Wells St')
(33, 'Paramount Room', 'Paramount Reuben', 13.0, '415 N. Milwaukee Ave')
(34, 'Melt Sandwich Shoppe', 'The Istanbul', 7.95, ' 1840 N. Damen Ave')
(35, 'Floriole Cafe & Bakery', 'B.A.D.', 9.0, '1220 W. Webster Ave')
(36, 'First Slice Pie Café', 'Duck Confit and Mozzarella', 9.0, '5357 N. Ashland Ave')
(37, 'Troquet', 'Croque Monsieur', 8.0, '1834 W. Montrose Ave')
(38, 'Grahamwich', 'Green Garbanzo', 8.0, '615 N. State St')
(39, 'Saigon Sisters', 'The Hen House', 7.0, 'Multiple location')
(40, 'Rosalia’s Deli', 'Tuscan Chicken', 6.0, '241 N. York Rd')
(41, 'Z&H MarketCafe', 'The Marty ', 7.25, ' 1323 E. 57th St')
(42, 'Market House on the Square', 'Whitefish', 11.0, '655 Forest Ave')
(43, 'Elaine’s Coffee Call', 'Oat Bread, Pecan Butter, and Fruit Jam', 6.0, 'Hotel Lincol')
(44, 'Marion Street Cheese Market', 'Cauliflower Melt', 9.0, '100 S. Marion St')
(45, 'Cafecito', 'Cubana', 5.49, ' 26 E. Congress Pkwy')
(46, 'Chickpea', 'Kufta', 8.0, '2018 W. Chicago Ave')
(47, 'The Goddess and Grocer', 'Debbie’s Egg Salad', 6.5, ' 25 E. Delaware Pl')
(48, 'Zenwich', 'Beef Curry', 7.5, ' 416 N. York St')
(49, 'Toni Patisserie', 'Le Végétarien', 8.75, ' 65 E. Washington St')
(50, 'Phoebe’s Bakery', 'The Gatsby', 6.85, ' 3351 N. Broadwa')

In [52]:
connect.close()

In [6]:
df

,Rank,Cafe,Menu,Price,Address
0,1,Old Oak Tap,BLT,10.00,2109 W. Chicago Ave
1,2,Au Cheval,Fried Bologna,9.00,800 W. Randolph St
2,3,Xoco,Woodland Mushroom,9.50,445 N. Clark St
3,4,Al’s Deli,Roast Beef,9.40,914 Noyes St
4,5,Publican Quality Meats,PB&L,10.00,825 W. Fulton Mkt
5,6,Hendrickx Belgian Bread Crafter,Belgian Chicken Curry Salad,7.25,100 E. Walton St
6,7,Acadia,Lobster Roll,16.00,1639 S. Wabash Ave
7,8,Birchwood Kitchen,Smoked Salmon Salad,10.00,2211 W. North Ave
8,9,Cemitas Puebla,Atomica Cemitas,9.00,3619 W. North Ave
9,10,Nana,Grilled Laughing Bird Shrimp and Fried Po’ Boy,17.00,3267 S. Halsted St
10,11,Lula Cafe,Ham and Raclette Panino,11.00,2537 N. Kedzie Blvd
11,12,Ricobene’s,Breaded Steak,5.49,Multiple location
12,13,Frog n Snail,The Hawkeye,14.00,3124 N. Broadwa
13,14,Crosby’s Kitchen,Chicken Dip,10.00,3455 N. Southport Ave
14,15,Longman & Eagle,Wild Boar Sloppy Joe,13.00,2657 N. Kedzie Ave
15,16,Bari,Meatball Sub,4.50,1120 W. Grand Ave
16,17,Manny’s,Corned Beef,11.95,1141 S. Jefferson St
17,18,Eggy’s,Turkey Club,11.50,333 E. Benton Pl
18,19,Old Jerusalem,Falafel,6.25,1411 N. Wells St
19,20,Mindy’s HotChocolate,Crab Cake,15.00,1747 N. Damen Ave
20,21,Olga’s Delicatessen,Chicken Schnitzel,5.00,3209 W. Irving Park Rd
21,22,Dawali Mediterranean Kitchen,Shawarma,6.00,Multiple location
22,23,Big Jones,Toasted Pimiento Cheese,8.00,5347 N. Clark St
23,24,La Pane,Vegetarian Panino,5.99,2954 W. Irving Park Rd
24,25,Pastoral,Cali Chèvre,7.52,Multiple location
25,26,Max’s Deli,Pastrami,11.95,191 Skokie Valley Rd
26,27,Lucky’s Sandwich Co.,The Fredo,7.50,Multiple location
27,28,City Provisions,Smoked Ham,12.95,1818 W. Wilson Ave
28,29,Papa’s Cache Sabroso,Jibarito,7.00,2517 W. Division St
29,30,Bavette’s Bar & Boeuf,Shaved Prime Rib,21.00,218 W. Kinzie St
30,31,Hannah’s Bretzel,Serrano Ham and Manchego Cheese,9.79,Multiple location
31,32,La Fournette,Tuna Salad,9.75,1547 N. Wells St
32,33,Paramount Room,Paramount Reuben,13.00,415 N. Milwaukee Ave
33,34,Melt Sandwich Shoppe,The Istanbul,7.95,1840 N. Damen Ave
34,35,Floriole Cafe & Bakery,B.A.D.,9.00,1220 W. Webster Ave
35,36,First Slice Pie Café,Duck Confit and Mozzarella,9.00,5357 N. Ashland Ave
36,37,Troquet,Croque Monsieur,8.00,1834 W. Montrose Ave
37,38,Grahamwich,Green Garbanzo,8.00,615 N. State St
38,39,Saigon Sisters,The Hen House,7.00,Multiple location
39,40,Rosalia’s Deli,Tuscan Chicken,6.00,241 N. York Rd
40,41,Z&H MarketCafe,The Marty,7.25,1323 E. 57th St
41,42,Market House on the Square,Whitefish,11.00,655 Forest Ave
42,43,Elaine’s Coffee Call,"Oat Bread, Pecan Butter, and Fruit Jam",6.00,Hotel Lincol
43,44,Marion Street Cheese Market,Cauliflower Melt,9.00,100 S. Marion St
44,45,Cafecito,Cubana,5.49,26 E. Congress Pkwy
45,46,Chickpea,Kufta,8.00,2018 W. Chicago Ave
46,47,The Goddess and Grocer,Debbie’s Egg Salad,6.50,25 E. Delaware Pl
47,48,Zenwich,Beef Curry,7.50,416 N. York St
48,49,Toni Patisserie,Le Végétarien,8.75,65 E. Washington St
49,50,Phoebe’s Bakery,The Gatsby,6.85,3351 N. Broadwa